packages:
  - "nftopia-frontend"
  - "nftopia-backend"
  - "nftopia-starknet"
  - "nftopia_analytics"
  - "nftopia-notification-service"
  - "nftopia-payment-service"
  - "nftopia-marketplace-service"
  - "nftopia-mobile-app"