# Generated by Django 5.2.3 on 2025-08-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=36)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'nftopia_payment_service.transaction',
                'abstract': False,
            },
        ),
    ]
