# Generated by Django 5.2.3 on 2025-08-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NftMint',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('mint_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'nftopia_user_service.nft_mints',
                'abstract': False,
                'managed': False,
            },
        ),
    ]
